version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/campus-navigation-app

permissions:
  - object: /home/ubuntu/campus-navigation-app/scripts
    pattern: "*.sh"
    owner: ubuntu
    group: ubuntu
    mode: 755

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: ubuntu

  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
      runas: ubuntu

  ApplicationStart:
    - location: scripts/start_application.sh
      timeout: 300
      runas: ubuntu
